sudo: false
dist: trusty
language: c
env:
  global:
    - secure: "QI0qw+0hitEfPcGNrX8pjw7peRBlO204z7bmHWNsvg/pCkzFVsGPsMm2nijn0Ey8gn8HyRR6wD6F4i4n3NTh2D4E03TWZmNtfxWjKqmalXQmQswdkByJeC+H211MQMrcQg8MaXPNbFzFeDWWn+YIkNbYySJO8IjYNfpGwxQ51kU="
matrix:
  include:
    - os: linux
      compiler: clang
      env: BUILD_TYPE=default CFLAGS='-fsanitize=address -fsanitize=undefined'
    - os: linux
      compiler: clang-5.0
      env: BUILD_TYPE=default CFLAGS='-fsanitize=address -fsanitize=undefined'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=default CFLAGS=-fsanitize=address
    - os: osx
      compiler: clang
      env: BUILD_TYPE=default CFLAGS=-fsanitize=address
    - os: linux
      compiler: clang
      env: BUILD_TYPE=coverage CFLAGS='-coverage -O0'
    - os: linux
      compiler: clang
      env: BUILD_TYPE=coverity
    - os: linux
      env: BUILD_TYPE=cppcheck
      addons:
        apt:
          packages:
            - cppcheck
    - os: osx
      env: BUILD_TYPE=mandoc
before_install:
  - |
    # Don't trigger Coverity unless it's a coverity build.
    if [ $BUILD_TYPE != coverity ]; then
      COVERITY_SCAN_BRANCH_PATTERN='^$'
    fi
    # Disable all builds while submitting to Coverity.
    if [ $TRAVIS_BRANCH = coverity_scan ]; then
      BUILD_TYPE=unknown
    fi
install:
  - |
    if [ $BUILD_TYPE = mandoc ]; then
      brew update
      brew install mandoc
    fi
script:
  - |
    (
    set -ex
    case $BUILD_TYPE in
    default)
      ./autogen.sh
      ./configure || (cat config.log; exit 1)
      make
      make distcheck || (find . -name test-suite.log | xargs -t cat; exit 1)
      ;;
    coverage)
      ./autogen.sh
      ./configure || (cat config.log; exit 1)
      make
      make check || (find . -name test-suite.log | xargs -t cat; exit 1)
      llvm-cov gcov pick-pick.c
      bash <(curl -s https://codecov.io/bash)
      ;;
    cppcheck)
      git ls-files | grep '\.c$' | cppcheck --quiet --error-exitcode=1 --file-list=-
      ;;
    mandoc)
      mandoc -Tlint -Wstyle pick.1
      ;;
    esac
    )
addons:
  coverity_scan:
    project:
      name: calleerlandsson/pick
      description: a fuzzy search tool for the command-line
    notification_email: pick-maintainers@calleerlandsson.com
    build_command_prepend: ./autogen.sh; ./configure
    build_command: make
    branch_pattern: coverity_scan
